def label = "worker-${UUID.randomUUID().toString()}"


podTemplate(label: label, containers: [
  // #0 필요한 Pod생성
]) {
  node(label) {

    // #1 Properties 파일 읽기

	// #6 예외처리 구문
	try {
		// #2 빌드 Stage
		stage('Build') {
			container('npm') {

			}
		}

		// #3 Sonarqube 정적분석 Stage
		stage('Static Code Analysis') {
			container('scanner') {

			}
		}

		// #4 컨테이너 이미지 생성 Stage
		stage('Dockerizing') {
			container('docker') {

			}
		}

		// #5 배포 Stage
		stage('Deploy') {
      			container('kubectl') {

      		}
    	}


	} catch(e) {
	}

  }

}
