apiVersion: v1
kind: Service
metadata:
  name: lab99-backend-svc
spec:
  type: NodePort
  selector:
    app: lab99-backend
  ports:
    - name: port-lab99-backend
      port: 8081
      targetPort: 3000
